name: Build 2021.1.2.7629

on:
  workflow_dispatch:

  push:
    branches: [ master ]
    paths:
      'Wwise 2021.1.2.7629/**'

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Login Docker
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} 
    
    - name: Build Wwise 2021.1.2.7629
      run: | 
        cp ./VC_redist.x64.exe "./Wwise 2021.1.2.7629" 
        cp Dockerfile "./Wwise 2021.1.2.7629" 
        docker build "./Wwise 2021.1.2.7629" --tag johnloser/wwise_windows:2021.1.2.7629
    - name: Push
      run: docker push --all-tags johnloser/wwise_windows
